/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_org_hellojni_HelloJni */

#ifndef _Included_com_org_hellojni_HelloJni
#define _Included_com_org_hellojni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_org_hellojni_HelloJni
 * Method:    getClanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_org_hellojni_HelloJni_getClanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
